[package]
name = "app"
version = "0.1.0-rc.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1.0.79"
rand = "0.8.4"
sqlx = { version = "0.7.3", features = ["mysql", "runtime-tokio-native-tls"] }
dotenv = "0.15.0"

[dev-dependencies]
tower = { version = "0.4.13", features = ["util"] }
